language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
before_script:
  - '[ "${TRAVIS_PYTHON_VERSION}" = "2.6" ] && pip install --use-mirrors futures ordereddict unittest2 || /bin/true'
  - "sudo apt-get install procmail"
  - "pip install --use-mirrors beautifulsoup4 PyYAML"
script: python setup.py test
