/* JS */ gapi.loaded_3(function(_){var window=this;
_.Xi=function(a,b){(0,_.ja)(b)||(b=[b]);var c=(0,_.Hg)(b,function(a){return(0,_.pa)(a)?a:a.wp+" "+a.duration+"s "+a.timing+" "+a.uf+"s"});(0,_.Di)(a,"transition",c.join(","))};
_.Yi=function(){if(!(0,_.fa)(Zi))if(_.V)Zi=(0,_.Rf)("10.0");else{var a=window.document.createElement("div"),b=_.kg?"-webkit":_.jg?"-moz":_.V?"-ms":_.ig?"-o":null;a.innerHTML='<div style="'+(b?b+"-transition:opacity 1s linear;":"")+'transition:opacity 1s linear;">';a=a.firstChild;b=a.style[(0,_.Bi)("transition")];Zi=""!=("undefined"!==typeof b?b:a.style[(0,_.Fi)(a,"transition")]||"")}return Zi};var Zi;

var Nz=function(a,b,c,d,e){this.width=a;this.height=b;this.A=c;this.B=d;this.opacity=e};var Oz=function(a,b,c,d){return new Nz(void 0==b?a.width:b,void 0==c?a.height:c,a.A,a.B,void 0==d?a.opacity:d)};_.Pz=function(a){_.Fw.call(this,a);this.Z=new _.Os(this)};
_.Qz=function(a){var b=+a.Re(200,"widgetWidth","width"),c=+a.Re(100,"widgetHeight","height"),d=a.Re("auto","corner"),e=a.Re({},"menuCss"),f=a.Re(!0,"hideOnClick");a.Ke=!!a.Re(!0,"hideOnLeave");a.Fc=!!a.Re((0,_.Yi)(),"useCss3Transition");a.ig=!!a.Re(!0,"allowOffset");var g=window.document.createElement("div");a.B=g;var k=(0,_.Iw)(a);k.parentNode.appendChild(g);var l=window.document.createElement("div");a.Q=l;g.appendChild(l);e.position="absolute";e.width=b+"px";e.height="0";e.border=e.border||"1px solid #aaa";
e.background=e.background||"#fff";e.zIndex=(0,_.Mw)(a);e.overflow="hidden";e.boxShadow=e.MozBoxShadow=e.webkitBoxShadow=e.boxShadow||"0 2px 2px rgba(0,0,0,0.3)";(0,_.Di)(g,e);(0,_.Di)(l,{left:"-1000px",top:"-1000px",position:"absolute",width:b+"px",height:c+"px"});a.ng=g.offsetWidth-b;a.rg=g.offsetHeight;e="auto"==d?["top","start"]:d.split("-");k=(0,_.Ys)(k);a.Aa="bottom"==e[0];a.Ea="right"==e[1]||"left"!=e[1]&&k;a.C=Rz(a,b,c,"auto"==d);a.Jb=_.s.setTimeout((0,_.x)(a.HG,a),500);a.Z.V(g,"mouseover",
a.sD);(0,_.Ps)(a.Z,g,"mouseout",a.rD,!1,a);f&&_.s.setTimeout((0,_.x)(function(){this.la||this.Z.V(window.document,"click",this.oE)},a),0)};
var Rz=function(a,b,c,d){var e=(0,_.Iw)(a),f=(0,_.ht)(e.offsetParent);f.right-=a.ng;f.bottom-=a.rg;if(d){var g=e.offsetLeft;d=g+b<f.right;g=g+e.offsetWidth-b>=f.left;a.Ea=a.Ea?!d||g:!d&&g;g=e.offsetTop;d=g+c<f.bottom;g=g+e.offsetHeight-c>=f.top;a.Aa=a.Aa?!d||g:!d&&g}d=Sz(a,a.Ea,e.offsetLeft,e.offsetWidth,b,f.left,f.right);a=Sz(a,a.Aa,e.offsetTop,e.offsetHeight,c,f.top,f.bottom);return new Nz(b,c,d,a,1)};
var Sz=function(a,b,c,d,e,f,g){return b?(a=c+d,Math.min(g-a,Math.max(f+e-a,0))):Math.max(f-c,Math.min(g-c-e,0))};var Tz=function(a,b,c){a.O.Ba().style.width=b+"px";a.O.Ba().style.height=c+"px";a.Q.style.width=b+"px";a.Q.style.height=c+"px";b=a.ig?Rz(a,b,c,!1):Oz(a.ob,b,c);a.C=b;a.I||Uz(a,b)};
_.Vz=function(a,b){Wz(a,Oz(b,void 0,0,0));_.s.setTimeout((0,_.x)(function(){this.I||(this.C=b,this.Fc&&(0,_.Xi)(this.B,"width 350ms cubic-bezier(.23, .50, .32, 1),height 350ms cubic-bezier(.23, .50, .32, 1),left 350ms cubic-bezier(.23, .50, .32, 1),top 350ms cubic-bezier(.23, .50, .32, 1),opacity 350ms cubic-bezier(.23, .50, .32, 1)"),Uz(this,b),this.Gj(!0,!1),this.pa&&(_.s.clearTimeout(this.pa),this.Va=!1),this.pa=_.s.setTimeout((0,_.x)(this.Gj,this,!0,!0),350))},a),0)};
var Xz=function(a){a.I||(a.Gj(!1,!1),Uz(a,Oz(a.ob,void 0,0,0)),a.I=!0,a.pa&&_.s.clearTimeout(a.pa),a.pa=_.s.setTimeout((0,_.x)(function(){this.pb=!0;this.Va?(Yz(this),this.Va=!1):(this.Fc&&(0,_.Xi)(this.B,""),this.B.visibility="hidden",this.B.left="-1000px",this.B.top="-1000px");this.Gj(!1,!0)},a),350))};var Yz=function(a){a.la=!0;(0,_.ah)(a.Z);a.Z=null;a.M&&(_.s.clearTimeout(a.M),a.M=null);a.W&&(_.s.clearTimeout(a.W),a.W=null);(0,_.fi)(a.B);a.B=null;(0,_.fi)((0,_.Iw)(a));a.Q=null;a.D=null};
var Uz=function(a,b){if(!a.I)if(a.Fc)Wz(a,b);else{var c=(0,_.za)()-20+350;a.W&&_.s.clearTimeout(a.W);a.Pu(a.ob,b,c)}};var Wz=function(a,b){var c=a.B,d=(0,_.Iw)(a);c.style.left=a.Ea?d.offsetLeft+d.offsetWidth+b.A-b.width+"px":d.offsetLeft+b.A+"px";c.style.width=b.width+"px";c.style.top=a.Aa?d.offsetTop+d.offsetHeight+b.B-b.height+"px":d.offsetTop+b.B+"px";c.style.height=b.height+"px";(0,_.Vi)(c,b.opacity);a.ob=b};
Nz.prototype.qe=function(a){return this.width==a.width&&this.height==a.height&&this.A==a.A&&this.B==a.B&&this.opacity==a.opacity};(0,_.z)(_.Pz,_.Hw);_.Pz.prototype.open=function(){(0,_.Qz)(this);this.O.fd(this.B);this.O.qb("resize",(0,_.x)(this.resize,this));this.O.mc("showMenu",(0,_.x)(this.Jw,this));var a=this.O.Cb;a.setHideOnLeave=(0,_.x)(this.ru,this);a.displayStateCallback&&(this.Nd=a.displayStateCallback,delete a.displayStateCallback);this.O.Mc(this.Q,{height:"100%"});(0,_.Vz)(this,this.C)};_.Pz.prototype.open=_.Pz.prototype.open;
_.Pz.prototype.Pb=function(a){this.la||(a=a||{},this.Q.style.left="0",this.Q.style.top="0",this.D&&((0,_.fi)(this.D),this.D=null),this.Jb&&(_.s.clearTimeout(this.Jb),this.Jb=null),Tz(this,(0,window.parseInt)(a.width,10)||(0,window.parseInt)(this.O.width,10)||this.C.width,(0,window.parseInt)(a.height,10)||(0,window.parseInt)(this.O.height,10)||this.C.height))};_.Pz.prototype.onready=_.Pz.prototype.Pb;
_.Pz.prototype.resize=function(a){this.la||Tz(this,(0,window.isNaN)(+a.width)?this.C.width:+a.width,(0,window.isNaN)(+a.height)?this.C.height:+a.height)};_.Pz.prototype.close=function(){this.pb?Yz(this):(this.Va=!0,Xz(this))};_.Pz.prototype.close=_.Pz.prototype.close;_.h=_.Pz.prototype;_.h.Re=function(a,b){for(var c,d=1,e=arguments.length;d<e&&(c=this.A[arguments[d]],void 0===c);++d);return void 0!==c?c&&"object"==typeof c?(d={},(0,_.Ci)(d,c),d):c:a};_.h.ru=function(a){this.Ke=!!a};
_.h.sD=function(){!this.I&&this.M&&(_.s.clearTimeout(this.M),this.M=null)};_.h.rD=function(a){if(!(this.I||this.M||!this.Ke||a.relatedTarget&&(0,_.ji)(this.B,a.relatedTarget))){var b=(0,_.gt)(this.B);a=a.clientY>b.top&&a.clientY<b.top+b.height?0:300;this.M=_.s.setTimeout((0,_.x)(this.Eo,this),a)}};_.h.oE=function(a){(0,_.Lw)(this.B,a)||this.Eo()};_.h.Jw=function(a){this.show(a||void 0===a)};_.h.show=function(a){a?!this.la&&this.pb&&(this.I=this.pb=!1,(0,_.Vz)(this,this.C)):this.Eo()};
_.h.Eo=function(){this.I||Xz(this)};_.h.Gj=function(a,b){var c=this.Nd;c&&_.s.setTimeout(function(){c(a,b)},0)};_.h.HG=function(){this.D=window.document.createElement("div");this.D.style.width=this.D.style.height="100%";this.D.style.position="absolute";this.D.style.background="url(//ssl.gstatic.com/ui/v1/activityindicator/loading_gs.gif) no-repeat "+(this.C.width-19)/2+"px "+(this.C.height-19)/2+"px";this.B.appendChild(this.D)};
_.h.Pu=function(a,b,c){this.W=null;if(!this.la&&!a.qe(b)){var d=(0,_.za)();if(d>=c)Wz(this,b);else{var d=Math.min(1-(c-d)/350,1),d=1-Math.pow(1-d,3),e=1-d,d=new Nz(Math.round(a.width*e+b.width*d),Math.round(a.height*e+b.height*d),Math.round(a.A*e+b.A*d),Math.round(a.B*e+b.B*d),a.opacity*e+b.opacity*d);Wz(this,d);this.W=_.s.setTimeout((0,_.x)(this.Pu,this,a,b,c),20)}}};

_.lf["slide-menu"]=function(a){var b=new _.Pz((0,_.AI)(a)),c=new _.Rw(b);b.open=function(){};(0,_.Qz)(b);a.attributes={height:"100%"};a.where=b.Q;a.onClose=function(){b.close()};a.onRestyle=function(a){if(a){var c=!1;a.hasOwnProperty("showMenu")&&(b.Jw(a.showMenu),c=!0);a.hasOwnProperty("setHideOnLeave")&&(b.ru(a.setHideOnLeave),c=!0);c||b.resize(a)}};a.onCreate=function(a){a.yb=function(){return this.ti("openerIframe")};c.O=b.O=a;a.fd(b.B);a.P("_ready",(0,_.x)(b.Pb,b),_.Ue);b.Nd=function(b,c){!a.gb()&& a.mh([b,c])};(0,_.Vz)(b,b.C);c.open()}};

});

// Copyright 2002-2013 Google Inc.
