/* JS */ gapi.loaded_2(function(_){var window=this;
_.pt=function(a,b,c){var d={},e;for(e in a)b.call(c,a[e],e,a)&&(d[e]=a[e]);return d};
_.Ew=function(){var a=window.document,b=0;if(a){var b=(0,_.si)(window).height,c=a.body,d=a.documentElement;if((0,_.ni)(a)&&d.scrollHeight)b=d.scrollHeight!=b?d.scrollHeight:d.offsetHeight;else{var a=d.scrollHeight,e=d.offsetHeight;d.clientHeight!=e&&(a=c.scrollHeight,e=c.offsetHeight);b=a>b?a>e?a:e:a<e?a:e}}return b};_.Fw=function(a){this.O=a;this.A=a.Oa()};
var Gw=function(a){var b=a.O.yb();if(a.A.anchorBox&&b&&b.Ba())b=(0,_.Ni)(b.Ba()),a.A.anchorBox.left+=b.x,a.A.anchorBox.top+=b.y;else{b=a.A.anchor;if("_default"!=b&&"_iframe"!=b){var c=(0,_.zi)(b);if(c)a.A.anchorBox=(0,_.gt)(c);else{(0,_.Ea)("Anchor not found in DOM: "+b+'. Falling back to "_default".');a.A.anchor="_default";return}}"_iframe"==b&&(b=(0,_.wi)(),a.A.anchorBox=new _.bt(0,0,b.width,b.height))}a.A.anchor=""};_.Hw=function(a){_.Fw.call(this,a)};
_.Iw=function(a){if(a.X)return a.X;var b=a.A;!b.anchorBox&&b.anchor&&Gw(a);var c=a.O.yb();if("_default"==b.anchor&&c){var d=(0,_.gt)((0,_.zi)(c.xa()));b.anchorBox=d}if(!b.anchorBox)return(0,_.Ea)("No anchor box defined."),null;b=new _.qi(b.anchorBox.left,b.anchorBox.top);c&&(c=(0,_.Oi)(c.Ba(),window),a.na=new _.qi,a.na.x=c.x,a.na.y=c.y,b.x+=c.x,b.y+=c.y,(0,_.Jw)(window,b));a.Ra=b;c=(0,_.Kw)(a,!0);a.X=window.document.createElement("ins");a.X.style.cssText=c;window.document.body.appendChild(a.X);return a.X};
_.Kw=function(a,b){var c=a.A;return"position: absolute !important;background-color: transparent !important;left: "+a.Ra.x+"px !important;top: "+a.Ra.y+"px !important;width: "+c.anchorBox.width+"px !important;height: "+c.anchorBox.height+"px !important;z-index: -10000 !important;display: "+(b?"block":"none")+" !important;"};
_.Lw=function(a,b){var c=0,d=0;if(b.pageX||b.pageY)c=b.pageX,d=b.pageY;else if(b.clientX||b.clientY){var d=b.target?b.target:b.srcElement,c=d.ownerDocument&&d.ownerDocument.parentWindow?d.ownerDocument.parentWindow:window,e=0,d=0;_.V?(e=c.document.documentElement.scrollLeft,d=c.document.documentElement.scrollTop):(e=c.pageXOffset,d=c.pageYOffset);c=b.clientX+e;d=b.clientY+d}d=new _.qi(c,d);return(c=(0,_.ct)((0,_.gt)(a)))&&c.contains(d)};
_.Jw=function(a,b){var c=window.document.body,d=(0,_.Ni)(c),c=c.currentStyle||a.getComputedStyle(c,"");c.position&&"static"!=c.position&&(b.x-=d.x,b.y-=d.y)};_.Mw=function(a){var b=a.O.yb()&&a.O.yb().xa(),b=b&&b.style.zIndex?(0,window.parseInt)(b.style.zIndex,10)+1:0;return Math.min(2147483647,Math.max(2E9,a.A.zIndex||b))};
_.Nw=function(a,b,c,d,e){e=e||{x:0,y:0};if(Ow[b]){var f=(0,_.Ti)(a).width/2;e.x="top-right"==d||"bottom-right"==d?e.x+f:e.x-f}Ow[d]&&(f=(0,_.Ti)(c).width/2,e.x+=f);Pw[b]&&(f=(0,_.Ti)(a).height/2,e.y="right-bottom"==d||"left-bottom"==d?e.y+f:e.y-f);Pw[d]&&(e.y+=(0,_.Ti)(c).height/2);(0,_.lt)(c,Qw[d],a,Qw[b],new _.qi(e.x,e.y));d=(0,_.jt)(a,function(a){return a==window.document?!1:(a=(0,_.Ji)(a))&&"static"!=a});c=b=0;d&&(c=(0,_.Ni)(d),b=-c.x,c=-c.y);a=a.style;(0,window.parseInt)(a.left,10)<b&&(a.left=
b+"px");(0,window.parseInt)(a.top,10)<c&&(a.top=c+"px")};_.Rw=function(a){_.Fw.call(this,a.O);this.F=a;this.B=null};var Sw=function(){_.Gh.call(this);this.A=[]};if("undefined"===typeof Tw)var Tw={};_.Fw.prototype.Ib=function(){Gw(this)};_.Fw.prototype.onBeforeParentOpen=_.Fw.prototype.Ib;
(0,_.z)(_.Hw,_.Fw);_.Hw.prototype.open=function(){var a=this.A,b=window.document.createElement("ins");window.document.getElementById(a.container).appendChild(b);b.style.display="block";(0,_.Di)(b,a.containerCss);this.O.fd(b);this.O.Mc(b)};_.Hw.prototype.Pb=function(){window.document.getElementById(this.O.id).style.height=this.O.height+"px"};_.Hw.prototype.close=function(){(0,_.fi)(this.O.xa());(0,_.fi)(this.X);this.X=null};
var Qw={"bottom-center":1,"bottom-end":7,"bottom-left":1,"bottom-right":3,"bottom-start":5,"left-bottom":1,"left-center":0,"left-top":0,"right-bottom":3,"right-center":2,"right-top":2,"top-center":0,"top-end":6,"top-left":0,"top-right":2,"top-start":4},Ow={"bottom-center":!0,"top-center":!0},Pw={"left-center":!0,"right-center":!0};
(0,_.z)(_.Rw,_.Hw);_.Rw.prototype.Ib=function(){this.F.Ib()};_.Rw.prototype.onBeforeParentOpen=_.Rw.prototype.Ib;_.Rw.prototype.open=function(){this.F.open();if(this.A.closeClickDetection||this.A.hideClickDetection)this.B=(0,_.rh)(window.document,["click","touchstart"],(0,_.x)(this.C,this),!1)};_.Rw.prototype.open=_.Rw.prototype.open;_.Rw.prototype.Pb=function(a){this.F.Pb(a)};_.Rw.prototype.onready=_.Rw.prototype.Pb;_.Rw.prototype.D=function(a){this.F.onRenderStart&&this.F.onRenderStart(a)};
_.Rw.prototype.onRenderStart=_.Rw.prototype.D;_.Rw.prototype.close=function(){if(this.A.closeClickDetection||this.A.hideClickDetection)(0,_.Ch)(this.B),this.B=null;this.F.close()};_.Rw.prototype.close=_.Rw.prototype.close;_.Rw.prototype.C=function(a){(0,_.Lw)(this.O.xa(),a)||(this.A.hideClickDetection&&this.F.show?this.F.show(!1):this.F.close())};
(0,_.z)(Sw,_.Gh);Sw.prototype.U=function(){for(var a in this.A)(0,_.Ch)(a);this.A=[];this.B=_.s.clearTimeout(this.B);Sw.N.U.call(this);this.dispatchEvent({type:"dispose"})};(0,_.p)("iframes.styles.createAnchor",function(){return new Sw(["email","oid","o","cid"])},void 0);

var CI;_.AI=function(a){return{Oa:function(){return a},yb:function(){return a.openerIframe}}};var BI=function(a){(new _.Fw((0,_.AI)(a))).Ib()};for(CI="bubble circlepicker float hover hover-menu slide-menu".split(" "),_.DI=0;_.DI<CI.length;_.DI++)_.hf[CI[_.DI]]=BI;

_.Bz=function(a){return(0,_.ti)((0,_.xi)((a||_.s||window).document))};_.Cz=function(a){_.Fw.call(this,a.O);this.F=a;this.B=null};_.Dz=function(a){_.Fw.call(this,a)};_.Ez=function(a,b){a.B=window.document.createElement("div");var c={position:"absolute",top:"-10000px",zIndex:(0,_.Mw)(a)};a.A.width&&(c.width=a.A.width+"px");for(var d in c)a.B.style[d]=c[d];(b||window.document.body).appendChild(a.B)};var Fz=function(a,b,c){for(a=0;a<Gz.length;a++)b.style[Gz[a]]=c?"opacity .13s linear":""};
var Hz=function(a,b,c){var d=a.O.yb();b+=10;c+=10;if(_.I.fa&&(d&&(d=(0,_.Oi)(d.xa(),window),b+=d.x,c+=d.y),d=Iz(a))){var e=(0,_.wi)(window),f=(0,_.Bz)(window);e.width&&(b=Math.min(b,e.width+f.x-d.width-8),c+d.height>e.height+f.y-8&&(c-=20+d.height,c=Math.max(c,Math.min(f.y+1,(0,_.Ew)()-d.height))))}a=a.O.xa();a.style.left=b+"px";a.style.top=c+"px"};
var Iz=function(a){return a.O.width&&a.O.height?{width:a.O.width,height:a.O.height}:(a=a.O.Ba())&&a.offsetWidth&&a.offsetHeight?{width:a.offsetWidth,height:a.offsetHeight}:null};_.Jz=function(a){_.Fw.call(this,a)};var Kz=function(a,b,c){a=a.split("-");for(var d=0;2>d;d++)b&&Lz[a[d]]&&(a[d]=Lz[a[d]]),c&&Mz[a[d]]&&(a[d]=Mz[a[d]]);return a.join("-")};(0,_.z)(_.Cz,_.Hw);
_.Cz.prototype.open=function(){this.A.targetPos=this.A.targetPos||"top-start";this.A.anchorPos=this.A.anchorPos||"bottom-start";var a=(0,_.Iw)(this),b=this.O.xa();b?(b.style.visibility="hidden",b.style.position="absolute",a.parentNode.appendChild(b)):this.F.open()};_.Cz.prototype.open=_.Cz.prototype.open;
_.Cz.prototype.Pb=function(){if(this.A.closeClickDetection){var a=this,b=function(b){(0,_.Lw)(a.O.xa(),b)||(a.O.close(),a.B=null)};window.document.A?(window.document.A("click",b),this.B=function(){window.document.removeEventListener("click",b,!1)}):window.document.attachEvent&&(window.document.attachEvent("onclick",b),this.B=function(){window.document.detachEvent("onclick",b)})}var c=this.O.xa();window.document.getElementById(this.O.id).style.height=this.O.height+"px";var d=(0,_.Iw)(this);d&&(0,_.Nw)(c,
this.A.targetPos,d,this.A.anchorPos,{x:this.A.leftOffset||0,y:this.A.topOffset||0});c.style.visibility="visible"};_.Cz.prototype.onready=_.Cz.prototype.Pb;_.Cz.prototype.close=function(){this.F.close();this.B&&this.B()};_.Cz.prototype.close=_.Cz.prototype.close;
(0,_.z)(_.Dz,_.Hw);var Gz=["transition","WebkitTransition","MozTransition","OTranstion","msTransition"];_.Dz.prototype.open=function(a){this.O.mc("updateContainer",(0,_.x)(this.C,this));(0,_.Ez)(this,a);this.O.Mc(this.B);this.O.fd(this.B)};_.Dz.prototype.open=_.Dz.prototype.open;_.Dz.prototype.Pb=function(){var a=Iz(this);if(a){var b=window.document.getElementById(this.O.Y());b.style.height=a.height+"px";b.style.width=a.width+"px";this.O.width=a.width;this.O.height=a.height;b.style.boxShadow="0 4px 16px rgba(0, 0, 0, 0.3)"}};
_.Dz.prototype.onready=_.Dz.prototype.Pb;_.Dz.prototype.close=function(){this.B.parentNode&&this.B.parentNode.removeChild(this.B)};_.Dz.prototype.close=_.Dz.prototype.close;_.Dz.prototype.C=function(a,b,c){var d=this.O.xa();d&&(a?(Hz(this,b,c),d.style.opacity=0,d.style.display="",window.setTimeout((0,_.x)(function(){Fz(this,d,!0);d.style.opacity=1},this),0)):(d.style.display="none",Fz(this,d,!1),d.style.opacity=0))};
(0,_.z)(_.Jz,_.Hw);_.Jz.prototype.C=null;_.Jz.prototype.D=null;_.Jz.prototype.B=null;var Lz={end:"start",left:"right",right:"left",start:"end"},Mz={top:"bottom",bottom:"top"};_.Jz.prototype.open=function(){var a=window.document.createElement("div");(0,_.Di)(a,{top:"-10000px",position:"absolute",zIndex:(0,_.Mw)(this)});(0,_.Iw)(this).parentNode.appendChild(a);this.O.fd(a);this.O.Mc(a)};_.Jz.prototype.open=_.Jz.prototype.open;
_.Jz.prototype.Pb=function(){var a=window.document.getElementById(this.O.id);a.style.height=this.O.height+"px";a.style.width=this.O.width+"px";a.style.boxShadow="0 4px 16px rgba(0, 0, 0, 0.3)";var b=this.O.xa();b.style.lineHeight=0;var c=(0,_.Iw)(this),d=this.A.targetPos||"top-start",e=this.A.anchorPos||"bottom-start",f=this.A.leftOffset||0,g=this.A.topOffset||0;(0,_.Nw)(b,d,c,e,{x:f,y:g});var k=(0,_.wi)(window),l=(0,_.Bz)(window),m=b.offsetLeft<l.x||b.offsetLeft+b.offsetWidth>k.width+l.x,k=b.offsetTop<
l.y||b.offsetTop+b.offsetHeight>k.height+l.y,d=Kz(d,m,k),e=Kz(e,m,k),f=f*(m?-1:1),g=g*(k?-1:1);(0,_.Nw)(b,d,c,e,{x:f,y:g});b.style.visibility="visible";this.C=(0,_.rh)(window.document,"mouseover",(0,_.x)(function(b){b.target===a&&this.B&&(window.clearTimeout(this.B),this.B=null)},this));this.D=(0,_.rh)(window.document,"mouseout",(0,_.x)(function(b){b.target===a&&(this.B=window.setTimeout((0,_.x)(this.O.close,this.O),1E3))},this))};_.Jz.prototype.onready=_.Jz.prototype.Pb; _.Jz.prototype.close=function(){this.C&&((0,_.Ch)(this.C),(0,_.Ch)(this.D),this.D=this.C=null);this.B&&(window.clearTimeout(this.B),this.B=null);_.Jz.N.close.call(this)};_.Jz.prototype.close=_.Jz.prototype.close;

_.lf.hover=function(a){var b=new _.Dz((0,_.AI)(a));(0,_.Ez)(b,a.where);a.where=b.B;a.onClose=function(){b.close()};a.onRestyle=function(a){if(a.updateContainer){var d=a.updateContainer;b.C(d.visible,d.x,d.y)}a.width&&(b.O.width=a.width);a.height&&(b.O.height=a.height)};a.onCreate=function(c){b.O=c;c.yb=function(){return a.openerIframe};c.P("_ready",(0,_.x)(b.Pb,b),_.Ue);c.updateContainer=function(a,c,f){b.C(a,c,f)}}};


var UD=function(a,b){this.A=a;this.wf=b};_.VD=function(a){this.w=this.ke=a;this.n=null;this.slf=0;this.ssh=!1;this.sen=!0;this.shl=this.itm=null};UD.prototype.gl=function(a){this.A.or(this.wf,a)};UD.prototype.el=function(){this.A.oc(this.wf)};_.VD.prototype.sm=function(a,b){this.ke.aG(new UD(a,this));this.n=b};_.VD.prototype.sh=function(){this.ke.show()};_.VD.prototype.hi=function(){this.ke.Ya()};_.VD.prototype.cl=function(){this.ke.close()};_.VD.prototype.en=function(){this.ke.enable()};_.VD.prototype.di=function(){this.ke.disable()};_.VD.prototype.hl=function(a){this.ke.BB(a)};_.VD.prototype.vr=function(a,b){this.ke.dC(a,b)};


var nH=function(a){this.A=a};_.oH=function(a){this.A=a||{}};_.pH=function(a,b){a.A.url=b;return a};_.qH=function(a,b){a.A.where=b;return a};nH.prototype.Fl=function(a){this.A.width=a;return this};nH.prototype.tc=function(){return this.A.width};nH.prototype.Wi=function(a){this.A.height=a;return this};nH.prototype.xb=function(){return this.A.height};
_.oH.prototype.value=function(){return this.A};_.oH.prototype.Nb=function(){return this.A.url};_.oH.prototype.Y=function(){return this.A.id};_.oH.prototype.Sn=function(){this.A.attributes=this.A.attributes||{};return new nH(this.A.attributes)};
var PI=function(a,b){a.A.messageHandlersFilter=b;return a};var QI=function(a,b){a.A.messageHandlers=b;return a};var RI=function(a,b){a.A.relayOpen=b;return a};var SI=function(a,b){a.A.queryParams=b;return a};var TI=function(a,b){a.A.style=b;return a};var UI=function(a,b){a.A.anchor=b;return a};var VI=function(a){this.A=a};var WI=function(a){a.A.os(a.wf)};var XI=function(a){this.wf=a;this.wc=0;this.bj=!1;this.js=!0;this.nf=null};var YI=function(a){return 5==a.wc||4==a.wc};
var ZI=function(a,b,c){this.A=a||{};this.B=b||0;this.D=c||0;a={};b=(0,_.x)(this.As,this);a.fc=b;b=(0,_.x)(this.Ap,this);a.rc=b;b=(0,_.x)(this.eq,this);a.sc=b;b=(0,_.x)(this.Ii,this);a.hc=b;b=(0,_.x)(this.Uh,this);a.cc=b;b=(0,_.x)(this.Nt,this);a.os=b;b=(0,_.x)(this.Mt,this);a.or=b;b=(0,_.x)(this.Kt,this);a.oh=b;b=(0,_.x)(this.It,this);a.oc=b;b=(0,_.x)(this.Jt,this);a.oe=b;b=(0,_.x)(this.Lt,this);a.oi=b;this.C=a};
var $I=function(a,b){if(a.B){var c=(0,window.setTimeout)((0,_.x)(function(){YI(b)||aJ(this,b)},a),a.B);b.nf=c}else aJ(a,b)};var aJ=function(a,b){var c=a.D-a.B;0<c&&(c=(0,window.setTimeout)((0,_.x)(function(){YI(b)||(b.wc=4,this.Uh(b.Qe()))},a),c),b.nf=c)};var bJ=function(a,b){null!=b.nf&&((0,window.clearTimeout)(b.nf),b.nf=null)};var cJ=function(a,b){bJ(a,b);b.wc=5;var c=a.A,d;for(d in c)c[d]==b&&delete c[d]};var dJ=function(a,b){return a.A[b.n]};var eJ=function(){ZI.call(this)};
var fJ=function(a){this.A=a};var gJ=function(){return window.___jsl.man};var hJ=function(a){if(window.___jsl.man)a(window.___jsl.man);else{var b=function(){var b=new eJ;window.___jsl.man=b;a(b)};if(window.gbar){var c=function(){if(window.gbar.wg){var c=new fJ(window.gbar.wg);window.___jsl.man=c;a(c)}else b()};window.gbar.wg?c():window.gbar.qm(c)}else b()}};
var iJ=function(a){var b=arguments.length;if(1==b&&(0,_.ja)(arguments[0]))return iJ.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};var jJ=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if((0,_.ja)(d)||(e=(0,_.oa)(d))&&Object.prototype.hasOwnProperty.call(d,"callee"))a.push.apply(a,d);else if(e)for(var f=a.length,g=d.length,k=0;k<g;k++)a[f+k]=d[k];else a.push(d)}};var kJ=function(a){return window.document.body==a?"body":a.__cardid||null};
var lJ=function(a){var b=kJ(a);b||(b=a.__cardid=mJ++);return b};var nJ=function(a){var b=a.className||"getAttribute"in a&&a.getAttribute("class");return b&&oJ.test(b)||"getAttribute"in a&&a.getAttribute("oid")&&36==(0,_.H)("card/p")?!0:"G:HOVERCARD"==a.tagName.toUpperCase()};
var pJ=function(a,b){var c={};(0,_.Vg)(c,qJ,(0,_.H)("iframes/card")||{},(0,_.H)("card")||{});for(var d=[],e=a;e;e=e.parentNode){var f=kJ(e);f&&b[f]&&d.push(b[f])}(0,_.Fg)(d.reverse(),function(a){(0,_.Vg)(c,a)});d="G:HOVERCARD"==a.tagName.toUpperCase()?"":"data-";e=a.attributes;for(f=0;f<e.length;f++)(0,_.Cf)(e[f].name,d)&&(c[e[f].name.substring(d.length)]=e[f].value);"getAttribute"in a&&a.getAttribute("oid")&&36==(0,_.H)("card/p")&&(c.ytid=a.getAttribute("oid"));!c.userid&&"A"==a.tagName.toUpperCase()&&
a.pathname&&(d=a.pathname.match(/^\/?(\d+)$/),/\.google\.com$/.test(a.hostname)&&d&&(c.userid=d[1]));c.hl||(c.hl=(0,_.H)("lang")||_.K.La().hl||void 0);c.m=c.entity;c.src=c.source;delete c.entity;delete c.source;return c};var rJ=function(a,b){var c=b[a];(0,_.xg)(c)||(c=qJ[a]);return 0>c?0:c};var sJ=function(a){this.A=a;this.wf=new _.VD(this);this.B=!1;this.C=0};
var tJ=function(a,b){WI(a.kc);var c=(0,_.pt)(b,function(a,b){return uJ[b]&&null!=a});c.origin=window.location.protocol+"//"+window.location.host;var d=a.A,e={_event:function(a){if(!(a.timestamp<d.Va)){"sgcp_ams"==a.event?(d.W=!0,d.na=!1):d.W&&"mouseover"==a.event?d.na=!0:d.W&&"mouseout"==a.event?d.na=!1:"sgcp_amh"==a.event&&(d.W=!1,d.na||vJ(d));if("mouseover"==a.event||"sgcp_ams"==a.event)window.clearTimeout(d.F),d.F=null;if(a.cpid){for(var b=window.document.getElementById(a.cpid);b&&"BODY"!=b.parentNode.tagName;)b=
b.parentNode;d.ob=b}a.fromCard&&"mouseout"==a.event&&vJ(d)}},_ready:(0,_.x)(a.iB,a),version:function(a){wJ(d,d.I,{type:"circles_changed",version:a.v})},loaded:function(b){b.ri==a.C&&a.D()},rendered:function(){var b=a.A.M,c=(0,_.Bz)(window);xJ(a,!0,b.x+c.x,b.y+c.y);b=a.A;wJ(b,b.I,{type:"show",frame:a.ta})},renderfailed:function(){xJ(a,!1,0,0)},disposed:function(){a.ta.close()},cardAction:function(a){yJ(d,a)}},f=":card";!(0,_.H)("iframes/card/url")&&(0,_.H)("iframes/hovercard/url")&&(f=":hovercard");
c=(0,_.pH)(TI(SI(PI(QI(new _.oH({disableMultiLevelParentRelay:!0,hover:!0}),e),_.Ue),c),"hover"),f);d.pa&&(RI(c,-1),UI(new VI(c.A),"_default"));_.bf.open(c.value(),(0,_.x)(function(a){this.ta=a},a))};var xJ=function(a,b,c,d){a.ta.updateContainer?a.ta.updateContainer(b,c,d):a.ta.Pv({updateContainer:{visible:b,x:c,y:d}})};
var zJ=function(){this.Jb=0;this.Ea=[];this.X={};this.Ra={};this.la={};this.Va=this.F=this.B=this.Q=this.pb=this.I=this.D=this.A=this.C=null;this.M={x:0,y:0};this.na=this.W=!1;this.ob=null;this.Aa=new _.tq;(0,_.Xg)("gapi.load")("gapi.iframes.style.slide-menu")};var AJ=function(a,b,c,d){var e=lJ(b),e=a.la[e]||(a.la[e]={});e[c]||(e[c]=d=(0,_.x)(d,a),b.addEventListener?b.addEventListener(c,d,"focus"==c||"blur"==c):("focus"==c?c="focusin":"blur"==c&&(c="focusout"),b.attachEvent("on"+c,d)))};
var BJ=function(a,b,c){(a=a.la[lJ(b)])&&a[c]&&(b.addEventListener?b.removeEventListener(c,a[c],"focus"==c||"blur"==c):b.detachEvent("focus"==c?"onfocusin":"blur"==c?"onfocusout":"on"+c,a[c]),delete a[c])};var CJ=function(a,b){var c=a.la[b.id];if(c)for(var d in c)c.hasOwnProperty(d)&&BJ(a,b,d)};var wJ=function(a,b,c){for(var d=[];b;){var e=kJ(b);e&&a.X[e]&&d.push(a.X[e]);b=b.parentNode}jJ(d,a.Ea);var f=!0;(0,_.Fg)(d,function(a){!1===a(c)&&(f=!1)});return f};
var vJ=function(a,b){a.A&&BJ(a,a.A,"mousemove");a.A=null;a.D=null;a.Q=null;a.B&&(window.clearTimeout(a.B),a.B=null);!a.F&&a.I&&(a.F=window.setTimeout((0,_.x)(a.Ao,a),(0,_.xg)(b)?b:rJ("closeDelay",a.pb)))};var yJ=function(a,b){wJ(a,null,b);a.Ib&&a.Ib.send("cardAction",b,void 0,a.pa)};VI.prototype.Wi=function(a){this.A.height=a;return this};VI.prototype.xb=function(){return this.A.height};VI.prototype.Fl=function(a){this.A.width=a;return this};VI.prototype.tc=function(){return this.A.width};
XI.prototype.Qe=function(){return this.wf};XI.prototype.isEnabled=function(){return this.js};XI.prototype.ib=function(a){this.js=a};_.h=ZI.prototype;_.h.Ap=function(a,b,c){try{a=a+(null!=b?"_"+b:""),c.sm(this.C,a),this.A[a]=new XI(c)}catch(d){return!1}return!0};_.h.As=function(a,b){var c=this.A[a+(null!=b?"_"+b:"")];return c?c.Qe():null};_.h.eq=function(a){var b=dJ(this,a);if(b&&(2==b.wc||3==b.wc)&&b.isEnabled()&&!b.bj){try{a.sh()}catch(c){}b.bj=!0}};
_.h.Ii=function(a){var b=dJ(this,a);if(b&&(2==b.wc||3==b.wc||YI(b))&&b.bj){try{a.hi()}catch(c){}b.bj=!1}};_.h.Uh=function(a){var b=dJ(this,a);if(b&&5!=b.wc){try{this.Ii(a),a.cl()}catch(c){}cJ(this,b)}};_.h.Nt=function(a){(a=dJ(this,a))&&0==a.wc&&($I(this,a),a.wc=1)};_.h.Mt=function(a){(a=dJ(this,a))&&!YI(a)&&1==a.wc&&(bJ(this,a),a.wc=3)};_.h.Kt=function(a){(a=dJ(this,a))&&!YI(a)&&(a.bj=!1)};_.h.It=function(a){var b=dJ(this,a);if(b&&!YI(b)){try{this.Ii(a)}catch(c){}cJ(this,b)}};
_.h.Jt=function(a){(a=dJ(this,a))&&!YI(a)&&(a.wc=4,this.Uh(a.Qe()))};_.h.Lt=function(a,b){var c=dJ(this,a);c&&!YI(c)&&2<=b&&4>=b&&!YI(c)&&(bJ(this,c),c.wc=2)};(0,_.z)(eJ,ZI);_.h=fJ.prototype;_.h.Ap=function(a,b,c){return this.A.rc(a,b,c)};_.h.As=function(a,b){return this.A.fc(a,b)};_.h.eq=function(a){this.A.sc(a)};_.h.Ii=function(a){this.A.hc(a)};_.h.Uh=function(a){this.A.cc(a)};_.h.Nt=function(a){this.A.os(a)};_.h.Mt=function(a,b){this.A.or(a,b)};_.h.Kt=function(a){this.A.oh(a)};_.h.It=function(a){this.A.oc(a)}; _.h.Jt=function(a,b,c,d,e,f){this.A.oe(a,b,c,d,e,f)};_.h.Lt=function(a,b,c,d){this.A.oi(a,b,c,d)};
var uJ=iJ("contactid","cmp","email","hl","n","m","p","src","usegapi","userid","sp","ytid");iJ("hl","origin","ri","src","userid");var DJ=iJ("nm","s","pr","v");(0,_.Vg)(DJ,uJ);var oJ=/(?:^|\s)g-(?:hovercard|profile)(?:$|\s)/,qJ={loadHovercardDelay:250,loadDelay:150,hoverDelay:500,closeDelay:500},mJ=0;_.h=sJ.prototype;_.h.Qe=function(){return this.wf};_.h.iB=function(){this.B=!0;this.kc.gl({});var a=this.A;a.A&&a.So(a.A)};_.h.aG=function(a){this.kc=a};_.h.BB=function(a){this.ta.send("getHealthc",void 0,a,_.Ue)};_.h.dC=function(a,b){this.ta.send("getVarc",a,b,_.Ue)};_.h.show=function(){xJ(this,!0,0,-1E4);this.ta.send("render",void 0,void 0,_.Ue)};_.h.Ya=function(){this.ta.send("hide",void 0,void 0,_.Ue);xJ(this,!1,0,0);var a=this.A;wJ(a,a.I,{type:"hide"});a.I=null;a.pb=null}; _.h.close=function(){this.ta.send("dispose",void 0,void 0,_.Ue)};_.h.enable=function(){};_.h.disable=function(){};
var EJ=0;_.h=zJ.prototype;_.h.watch=function(a,b,c){if(a=a||window.document.body){this.Jb++;var d=lJ(a);b&&(this.X[d]=b);c&&(this.Ra[d]=c);AJ(this,a,"mouseover",this.Ht);AJ(this,a,"mouseout",this.xo);AJ(this,a,"mousedown",this.Ft);AJ(this,a,"focus",this.Ht);AJ(this,a,"blur",this.xo);AJ(this,window.document.body,"mouseout",this.xo);AJ(this,window.document.body,"mousedown",this.Ft)}else window.setTimeout((0,_.x)(this.watch,this),100)};
_.h.unwatch=function(a){if(a=a||window.document.body)if(vJ(this,0),a!=window.document.body?CJ(this,a):BJ(this,window.document.body,"mouseover"),a=lJ(a),delete this.X[a],delete this.Ra[a],!(0<--this.Jb)){CJ(this,window.document.body);var b=this.C;this.Ao();this.C=null;window.setTimeout(function(){var a=gJ();a&&a.Uh(b.Qe())},100)}};_.h.qb=function(a){this.Ea.push(a)};_.h.Of=function(a){(0,_.Ag)(this.Ea,a)};
_.h.Ht=function(a){this.Va=(0,_.za)();var b=a.target||a.srcElement;if(b&&"IFRAME"!=b.tagName){for(;b&&!nJ(b);)if(b=b.parentNode,1!=b.nodeType)return;if(b)if(this.I==b||this.A==b)this.F&&(window.clearTimeout(this.F),this.F=null);else{this.A=b;AJ(this,b,"mousemove",this.DC);"focus"==a.type||"focusin"==a.type?(a=(0,_.at)(b),this.M.x=a.x,this.M.y=a.y+b.offsetHeight):(this.M.x=a.clientX,this.M.y=a.clientY);this.Q=(0,_.za)();a=this.D=pJ(b,this.Ra);a.usegapi=(0,_.H)("card/usegapi");var c=rJ("hoverDelay",
a);this.C?this.C.B&&(window.clearTimeout(this.B),this.B=window.setTimeout((0,_.x)(this.So,this,b),c-rJ("loadDelay",a))):(window.clearTimeout(this.B),this.B=window.setTimeout((0,_.x)(this.VD,this),c-rJ("loadHovercardDelay",a)))}}};_.h.xo=function(a){this.Va=(0,_.za)();if("blur"!=a.type||a.target==this.I||a.target==this.A){if(a=a.relatedTarget||a.toElement){if("IFRAME"==a.tagName)return;if(this.ob)for(;a&&"BODY"!=a.tagName;){if(a==this.ob)return;a=a.parentNode}}vJ(this)}};
_.h.Ft=function(){vJ(this,0)};_.h.DC=function(a){this.M.x=a.clientX;this.M.y=a.clientY};_.h.VD=function(){this.B&&(window.clearTimeout(this.B),this.B=null);if(this.A&&(wJ(this,this.A,{type:"hover",config:this.D}),!this.C)){var a=this.C=new sJ(this);hJ((0,_.x)(function(b){b.Ap("card",EJ++,a.Qe())&&tJ(a,this.D)},this))}};
_.h.So=function(a){this.B&&(window.clearTimeout(this.B),this.B=null);if(this.A==a){var b=rJ("hoverDelay",this.D)-rJ("loadDelay",this.D)-(0,_.za)()+this.Q;if(0<b)this.B=window.setTimeout((0,_.x)(this.So,this,a),b);else{wJ(this,a,{type:"hover",config:this.D});var b=this.C,c=this.D;a=(0,_.x)(this.Hw,this,a);b.B&&(b.D=a,c.ri=++b.C,b.ta.send("loadData",c,void 0,_.Ue))}}};
_.h.Hw=function(a){if(this.A===a&&this.C&&this.C.B&&this.Q){var b=rJ("hoverDelay",this.D)-(0,_.za)()+this.Q;0<b?window.setTimeout((0,_.x)(this.Hw,this,a),b):(this.Ao(),this.I=this.A,this.pb=this.D,BJ(this,this.A,"mousemove"),this.Q=this.D=this.A=null,gJ().eq(this.C.Qe()))}};_.h.Ao=function(){this.F&&(window.clearTimeout(this.F),this.F=null);this.I&&gJ().Ii(this.C.Qe())};
_.h.Jm=function(a,b,c){var d={};d.frame=a;d.filter=b||_.Te;d.Wa=c||_.zg;this.Aa.set((0,_.Sh)(a),d);a.P("cardAction",(0,_.x)(function(a){yJ(this,a);d.Wa(a)},this),d.filter)};_.h.Km=function(a){this.pa=a||_.Te;_.bf.D((0,_.x)(function(a){this.Ib=a;this.Ib.P("cardAction",(0,_.x)(this.Ej,this),this.pa)},this),void 0,this.pa)};_.h.Ej=function(a){this.Aa.vc()||(0,_.Fg)(this.Aa.Ob(),function(b){b.frame.send("cardAction",a,void 0,b.filter)});this.C&&this.C.ta.send("cardAction",a,void 0,_.Ue)};
_.FJ=function(){var a={},b=new zJ;a.watch=function(a,d,e){b.watch(a,d,e)};a.unwatch=function(a){b.unwatch(a)};a.qb=function(a){b.qb(a)};a.Of=function(a){b.Of(a)};a.Jm=function(a,d,e){b.Jm(a,d,e)};a.Km=function(a){b.Km(a)};a.Ej=function(a){b.Ej(a)};a.ca=function(a,b){b.origin=window.location.protocol+"//"+window.location.host;var e=_.bf.dh({url:":card",where:window.document.getElementById(a),queryParams:b,messageHandlers:{_ready:function(){e.send("loadData",b,void 0,_.Ue)},loaded:function(){e.send("render", void 0,void 0,_.Ue)}},messageHandlersFilter:_.Ue})};return a}();
(0,_.p)("gapi.card.watch",_.FJ.watch,void 0);(0,_.p)("gapi.card.unwatch",_.FJ.unwatch,void 0);(0,_.p)("gapi.card.addCallback",_.FJ.qb,void 0);(0,_.p)("gapi.card.removeCallback",_.FJ.Of,void 0);(0,_.p)("gapi.card.render",_.FJ.ca,void 0);(0,_.p)("gapi.card.connectChild",_.FJ.Jm,void 0);(0,_.p)("gapi.card.connectOpener",_.FJ.Km,void 0);(0,_.p)("gapi.card.broadcast",_.FJ.Ej,void 0);

});

// Copyright 2002-2013 Google Inc.
